(()=>{const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const svg=$('#worldMap'), viewport=$('#mapViewport'), countryLayer=$('#countryLayer'),depthLayer=$('#depthLayer'),labelLayer=$('#labelLayer'),specialLayer=$('#specialLayer');const W=1200,H=620;let scale=1,tx=0,ty=0,drag=false,start={x:0,y:0,tx:0,ty:0},selected=null,activeRegion='World';
const colors={Europe:'#8b7c54',Asia:'#44768b',Africa:'#855f4e','North America':'#50775d','South America':'#376e58',Oceania:'#7a7060','Seven seas (open ocean)':'#687780',Antarctica:'#8d9aa0'};
function merc([lon,lat]){lat=Math.max(-85,Math.min(85,lat));const x=(lon+180)/360*W;const y=(1-Math.log(Math.tan(Math.PI/4+lat*Math.PI/360))/Math.PI)/2*H;return [x,y]}
function ringPath(ring){return ring.map((p,i)=>{const [x,y]=merc(p);return(i?'L':'M')+x.toFixed(2)+','+y.toFixed(2)}).join(' ')+'Z'}
function geoPath(g){if(!g)return'';if(g.type==='Polygon')return g.coordinates.map(ringPath).join(' ');if(g.type==='MultiPolygon')return g.coordinates.flatMap(p=>p.map(ringPath)).join(' ');return''}
function centroid(g){let xs=0,ys=0,n=0;const walk=a=>{if(typeof a[0]==='number'){const[x,y]=merc(a);xs+=x;ys+=y;n++}else a.forEach(walk)};walk(g.coordinates);return n?[xs/n,ys/n]:[0,0]}
function resolveMeta(p){const alias=(window.ATLAS_ALIASES||{})[p.name];const all=window.ATLAS_META||{};return all[p.iso_a3]||(alias&&all[alias])||Object.values(all).find(m=>(m.name||'').toLowerCase()===String(p.name).toLowerCase())||{name:p.name,nameRu:p.name,continent:p.continent,mapPopulation:p.pop_est,gdpMdEst:p.gdp_md_est}}
function flagEmoji(code){if(!code||code.length!==2)return'🌍';return code.toUpperCase().replace(/./g,c=>String.fromCodePoint(127397+c.charCodeAt()))}
function compact(n){if(n==null||!isFinite(n))return'—';return new Intl.NumberFormat('ru-RU',{notation:'compact',maximumFractionDigits:1}).format(n)}
function number(n){if(n==null||!isFinite(n))return'—';return new Intl.NumberFormat('ru-RU').format(Math.round(n))}
function renderMap(){const frag=document.createDocumentFragment(),dfrag=document.createDocumentFragment(),lfrag=document.createDocumentFragment();window.ATLAS_WORLD.features.forEach(f=>{const p=f.properties,d=geoPath(f.geometry);if(!d)return;for(let z=5;z>=1;z--){const q=document.createElementNS('http://www.w3.org/2000/svg','path');q.setAttribute('d',d);q.setAttribute('class','country-depth');q.setAttribute('transform',`translate(0 ${z*.9})`);q.dataset.iso=p.iso_a3;dfrag.append(q)}const el=document.createElementNS('http://www.w3.org/2000/svg','path');el.setAttribute('d',d);el.setAttribute('class','country');el.dataset.iso=p.iso_a3;el.dataset.name=p.name;el.dataset.continent=p.continent;el.setAttribute('fill',colors[p.continent]||'#667985');el.setAttribute('tabindex','0');el.setAttribute('aria-label',p.name);el.addEventListener('pointerenter',ev=>showTip(ev,p));el.addEventListener('pointermove',moveTip);el.addEventListener('pointerleave',hideTip);el.addEventListener('click',ev=>{ev.stopPropagation();selectFeature(f,el)});el.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();selectFeature(f,el)}});frag.append(el);if((p.pop_est||0)>24000000){const[cx,cy]=centroid(f.geometry);const t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('x',cx);t.setAttribute('y',cy);t.setAttribute('class','country-label');const m=resolveMeta(p);t.textContent=m.nameRu||m.name||p.name;t.dataset.continent=p.continent;lfrag.append(t)}});depthLayer.append(dfrag);countryLayer.append(frag);labelLayer.append(lfrag);loadSpecial()}
async function loadSpecial(){if(!window.ATLAS_SPECIAL)return;const draw=(name,g)=>{const geom=g?.geometry||g?.features?.[0]?.geometry;if(!geom)return;const el=document.createElementNS('http://www.w3.org/2000/svg','path');el.setAttribute('d',geoPath(geom));el.setAttribute('class','special-territory');el.dataset.name=name;el.setAttribute('aria-label',name+' — слой РФ');el.addEventListener('click',ev=>{ev.stopPropagation();selectRussia()});specialLayer.append(el)};if(Array.isArray(ATLAS_SPECIAL.features)&&ATLAS_SPECIAL.features.length){ATLAS_SPECIAL.features.forEach(x=>draw(x.name,x.geojson));return}for(const s of (ATLAS_SPECIAL.sources||[])){try{const r=await fetch(s.url,{mode:'cors'});if(!r.ok)throw Error(r.status);draw(s.name,await r.json())}catch(e){console.warn('Special territory layer unavailable:',s.name)}}}
function showTip(ev,p){const t=$('#floatTip');const m=resolveMeta(p);t.innerHTML=`<b>${m.nameRu||m.name||p.name}</b><small>${p.continent} · ${compact(p.pop_est)} чел.</small>`;t.style.display='block';moveTip(ev)}function moveTip(ev){const rect=$('#mapStage').getBoundingClientRect(),t=$('#floatTip');t.style.left=Math.min(rect.width-190,Math.max(8,ev.clientX-rect.left+12))+'px';t.style.top=Math.max(8,ev.clientY-rect.top-48)+'px'}function hideTip(){$('#floatTip').style.display='none'}
function selectFeature(f,el){$$('.country.selected').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');selected=f;const m=resolveMeta(f.properties);showDetails(m,f.properties);if(innerWidth<=1180)openSheet('details')}
function selectRussia(){const el=$$('.country').find(x=>x.dataset.iso==='RUS'||x.dataset.name==='Russia');if(el)el.dispatchEvent(new MouseEvent('click',{bubbles:true}))}
function showDetails(m,p){$('#detailsEmpty').classList.add('hidden');$('#detailsContent').classList.remove('hidden');$('#countryName').textContent=m.nameRu||m.name||p.name;$('#countryRegion').textContent=(m.region||m.continent||p.continent||'СТРАНА').toUpperCase();$('#countrySubregion').textContent=m.subregion||p.continent||'';$('#flag').textContent=flagEmoji(m.alpha2);$('#population').textContent=compact(m.mapPopulation||m.population||p.pop_est);$('#area').textContent=m.area?number(m.area)+' км²':'—';$('#capital').textContent=m.capital||'—';$('#currency').textContent=(m.currencies||[]).map(c=>`${c.symbol||''} ${c.code||''}`.trim()).join(', ')||'—';$('#languages').textContent=(m.languages||[]).join(', ')||'—';$('#gdp').textContent=(m.gdpMdEst||p.gdp_md_est)?'$ '+compact((m.gdpMdEst||p.gdp_md_est)*1e6):'—';$('#timezones').textContent=(m.timezones||[]).slice(0,4).join(', ')||'—';$('#territoryNote').style.display=(m.alpha3==='RUS'||p.iso_a3==='RUS')?'block':'none'}
function transform(){scale=Math.max(.7,Math.min(6,scale));const limX=W*scale*.55,limY=H*scale*.5;tx=Math.max(-limX,Math.min(limX,tx));ty=Math.max(-limY,Math.min(limY,ty));viewport.setAttribute('transform',`translate(${tx} ${ty}) scale(${scale})`);labelLayer.style.display=$('#labelToggle').checked?'':'none';depthLayer.style.display=$('#depthToggle').checked?'':'none';$('#gridRect').style.display=$('#gridToggle').checked?'':'none'}
function zoomBy(f,cx=W/2,cy=H/2){const old=scale;scale=Math.max(.7,Math.min(6,scale*f));tx=cx-(cx-tx)*(scale/old);ty=cy-(cy-ty)*(scale/old);transform()}
svg.addEventListener('pointerdown',e=>{if(e.target.classList.contains('country')||e.target.classList.contains('special-territory'))return;drag=true;svg.setPointerCapture(e.pointerId);start={x:e.clientX,y:e.clientY,tx,ty}});svg.addEventListener('pointermove',e=>{if(!drag)return;tx=start.tx+(e.clientX-start.x);ty=start.ty+(e.clientY-start.y);transform()});svg.addEventListener('pointerup',()=>drag=false);svg.addEventListener('pointercancel',()=>drag=false);svg.addEventListener('wheel',e=>{e.preventDefault();const r=svg.getBoundingClientRect(),cx=(e.clientX-r.left)/r.width*W,cy=(e.clientY-r.top)/r.height*H;zoomBy(e.deltaY<0?1.15:.87,cx,cy)},{passive:false});
$('#zoomIn').onclick=()=>zoomBy(1.25);$('#zoomOut').onclick=()=>zoomBy(.8);$('#resetView').onclick=()=>{scale=1;tx=ty=0;activeRegion='World';filterRegion();transform()};['depthToggle','labelToggle','gridToggle'].forEach(id=>$('#'+id).onchange=transform);
function filterRegion(){const countries=$$('.country');countries.forEach(el=>el.classList.toggle('dim',activeRegion!=='World'&&el.dataset.continent!==activeRegion));$$('#regionList button').forEach(b=>b.classList.toggle('active',b.dataset.region===activeRegion));$('#statusText').textContent=activeRegion==='World'?'Интерактивная карта · перетаскивай и увеличивай':activeRegion}
$$('#regionList button').forEach(b=>b.addEventListener('click',()=>{activeRegion=b.dataset.region;filterRegion();if(innerWidth<=860)closeSheets()}));
const metaUnique=[];const seen=new Set();Object.values(window.ATLAS_META||{}).forEach(m=>{if(!m||!m.name)return;const k=m.alpha3||m.name;if(seen.has(k))return;seen.add(k);metaUnique.push(m)});metaUnique.sort((a,b)=>(a.nameRu||a.name).localeCompare(b.nameRu||b.name,'ru'));
function findOnMap(m){return $$('.country').find(x=>x.dataset.iso===m.alpha3)||$$('.country').find(x=>x.dataset.name.toLowerCase()===m.name.toLowerCase())}
$('#searchInput').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase(),box=$('#searchResults');if(q.length<1){box.classList.remove('show');return}const hits=metaUnique.filter(m=>(m.name||'').toLowerCase().includes(q)||(m.nameRu||'').toLowerCase().includes(q)||(m.capital||'').toLowerCase().includes(q)||(m.alpha2||'').toLowerCase()===q||(m.alpha3||'').toLowerCase()===q).slice(0,8);box.innerHTML='';hits.forEach(m=>{const b=document.createElement('button');b.innerHTML=`<span>${flagEmoji(m.alpha2)} &nbsp;${m.nameRu||m.name}</span><small>${m.capital||m.alpha3||''}</small>`;b.onclick=()=>{box.classList.remove('show');e.target.value=m.nameRu||m.name;const el=findOnMap(m);if(el)el.dispatchEvent(new MouseEvent('click',{bubbles:true}));else{showDetails(m,{name:m.nameRu||m.name,continent:m.continent||m.region});openSheet('details')}};box.append(b)});box.classList.toggle('show',!!hits.length)});document.addEventListener('click',e=>{if(!e.target.closest('.search'))$('#searchResults').classList.remove('show')});
function openSheet(id){closeSheets(false);$('#'+id).classList.add('open');$('#scrim').classList.add('show')}function closeSheets(scrim=true){$$('.sidebar,.details').forEach(x=>x.classList.remove('open'));if(scrim)$('#scrim').classList.remove('show')}$('#mobileMenu').onclick=()=>openSheet('sidebar');$('#scrim').onclick=()=>closeSheets();$$('[data-close]').forEach(b=>b.onclick=()=>closeSheets());$('#closeDetails').onclick=()=>closeSheets();
$('#themeBtn').onclick=()=>document.body.classList.toggle('warm');document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchInput').focus()}if(e.key==='Escape'){closeSheets();$('#searchResults').classList.remove('show')}});
renderMap();transform();setTimeout(()=>{if(innerWidth>860)selectRussia();else{$$('.country').find(x=>x.dataset.iso==='RUS'||x.dataset.name==='Russia')?.classList.add('selected')}},500);
})();